steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/${PROJECT_ID}/weather-latest1', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/weather-latest1']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'weather-latest1', '--image', 'gcr.io/${PROJECT_ID}/weather-latest1', '--platform', 'managed', '--region', 'us-central1']
